
services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
      - "5005:5005"   # Debug port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dbbox
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    depends_on:
      postgres:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - app-net
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: dbbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  pgdata:
